version: '3.3'
services:

  Notary:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 2.0.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10002:10002"
      - "10003:10003"
      - "10004:10004"
    image: corda/node:2.0
    container_name: notary
    volumes:
      - ./nodes/notary/corda-notary.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/notary/certificates/:/opt/corda/certificates/

  CordaNetworkMap:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 2.0.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10012:10002"
      - "10013:10003"
      - "10014:10004"
    image: corda/networkmap:2.0
    container_name: networkmap
    volumes:
      - ./nodes/networkmap/corda-networkmap.conf:/opt/corda/node.conf

  CordaNodeA:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 2.0.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10022:10002"
      - "10023:10003"
      - "10024:10004"
    image: corda/node:2.0
    container_name: banka
    volumes:
      - ./nodes/banka/corda-banka.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/banka/certificates/:/opt/corda/certificates/
    depends_on:
      - CordaNetworkMap

  CordaNodeB:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 2.0.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10032:10002"
      - "10033:10003"
      - "10034:10004"
    image: corda/node:2.0
    container_name: bankb
    volumes:
      - ./nodes/bankb/corda-bankb.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/bankb/certificates/:/opt/corda/certificates/
    depends_on:
      - CordaNetworkMap

  CordaNodeC:
    networks:
      - corda
    build:
      context: .
      args:
        BUILDTIME_CORDA_VERSION: 2.0.0
    env_file:
      - ./corda_docker.env
    ports:
      - "10042:10002"
      - "10043:10003"
      - "10044:10004"
    image: corda/node:2.0
    container_name: bankc
    volumes:
      - ./nodes/bankc/corda-bankc.conf:/opt/corda/node.conf
      - ./plugins/:/opt/corda/plugins/
      - ./nodes/bankc/certificates/:/opt/corda/certificates/
    depends_on:
      - CordaNetworkMap

networks:
  corda:
